# Generated by Django 6.0.2 on 2026-03-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='sport',
            field=models.CharField(default='badminton', max_length=20),
        ),
    ]
