# Generated by Django 6.0.2 on 2026-03-06 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_sport'),
        ('users', '0002_user_sport_pref'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='partner1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_partner1', to='users.user'),
        ),
        migrations.AddField(
            model_name='game',
            name='partner2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_partner2', to='users.user'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('rotation_doubles', '多人轮转双打'), ('round_robin', '单打循环赛'), ('knockout', '单打淘汰赛'), ('group', '单打分组赛')], default='round_robin', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('open', '报名中'), ('paused', '已暂停'), ('ongoing', '进行中'), ('finished', '已结束'), ('cancelled', '已取消')], default='draft', max_length=20),
        ),
    ]
