# Generated by Django 6.0.2 on 2026-03-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_game_partner1_game_partner2_alter_match_match_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner_team',
            field=models.CharField(blank=True, choices=[('team1', '队伍1'), ('team2', '队伍2'), ('draw', '平局')], max_length=10, null=True),
        ),
    ]
