# Generated by Django 6.0.2 on 2026-03-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_game_winner_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='match',
            name='city',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='match',
            name='country',
            field=models.CharField(blank=True, default='中国', max_length=30),
        ),
        migrations.AddField(
            model_name='match',
            name='district',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='match',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='province',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
