# Generated by Django 6.0.2 on 2026-03-01 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('match_type', models.CharField(choices=[('round_robin', '循环赛'), ('knockout', '淘汰赛'), ('group', '分组赛')], default='round_robin', max_length=20)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('open', '报名中'), ('ongoing', '进行中'), ('finished', '已结束')], default='draft', max_length=20)),
                ('max_players', models.IntegerField(default=16)),
                ('group_size', models.IntegerField(default=4)),
                ('levels', models.JSONField(default=list)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('need_approve', models.BooleanField(default=False)),
                ('allow_team', models.BooleanField(default=False)),
                ('contact_name', models.CharField(blank=True, default='', max_length=50)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('register_start', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_matches', to='users.user')),
            ],
            options={
                'verbose_name': '赛事',
                'verbose_name_plural': '赛事列表',
                'db_table': 'matches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_num', models.IntegerField(default=1)),
                ('score1', models.IntegerField(blank=True, null=True)),
                ('score2', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '待赛'), ('ongoing', '进行中'), ('finished', '已完成')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_p1', to='users.user')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_p2', to='users.user')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to='users.user')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='matches.match')),
            ],
            options={
                'verbose_name': '场次',
                'verbose_name_plural': '场次列表',
                'db_table': 'games',
                'ordering': ['round_num', 'id'],
            },
        ),
    ]
