"""
真实球拍数据 - 基于公开规格整理
图片来源：各品牌官网 CDN
"""

RACKETS = [
  # ───────────────── 羽毛球拍 ─────────────────
  {
    "sport":"badminton","brand":"Yonex","model":"Astrox 99 Pro",
    "image":"https://www.yonex.com/media/catalog/product/a/x/ax99p_wh_main_1.jpg",
    "price":1680,"weight_g":83,"balance":"head_heavy","flex":"stiff",
    "skill_level":"advanced","gender":"male",
    "shaft_material":"HM Graphite + Namd","frame_material":"HM Graphite + Tungsten",
    "string_tension":"20-28磅","head_size_cm2":68,"length_mm":675,
    "description":"Yonex 旗舰进攻型球拍，搭载 Namd 纳米技术纤维，拍杆存储更多能量并快速释放，提供毁灭性扣杀力量。林丹等世界顶级球员使用。",
    "highlights":["Namd纳米纤维提升弹性","2层钨合金框架增重心","世界冠军级扣杀力量"],
    "tags":["进攻","扣杀","专业"],
    "suitable_height_min":165,"suitable_height_max":210,
    "suitable_weight_min":60,"suitable_weight_max":100,
    "suitable_age_min":16,"suitable_age_max":45,
  },
  {
    "sport":"badminton","brand":"Yonex","model":"Astrox 88D Pro",
    "image":"https://www.yonex.com/media/catalog/product/a/x/ax88dp_wbo_main_1.jpg",
    "price":1480,"weight_g":83,"balance":"head_heavy","flex":"stiff",
    "skill_level":"advanced","gender":"unisex",
    "shaft_material":"HM Graphite","frame_material":"HM Graphite + Tungsten",
    "string_tension":"20-28磅","head_size_cm2":68,"length_mm":675,
    "description":"专为双打后场攻击手设计，强化拍头配重使扣杀更具威胁，拍框弧形设计提升拍线床稳定性，适合爱好大力扣杀的双打选手。",
    "highlights":["双打后场专属设计","拍头配重增强扣杀","同系列D为进攻S为速度"],
    "tags":["进攻","双打","后场"],
    "suitable_height_min":165,"suitable_height_max":210,
    "suitable_weight_min":55,"suitable_weight_max":100,
    "suitable_age_min":16,"suitable_age_max":45,
  },
  {
    "sport":"badminton","brand":"Yonex","model":"Nanoflare 800 Pro",
    "image":"https://www.yonex.com/media/catalog/product/n/f/nf800p_main_1.jpg",
    "price":1580,"weight_g":83,"balance":"head_light","flex":"stiff",
    "skill_level":"advanced","gender":"unisex",
    "shaft_material":"HM Graphite","frame_material":"HM Graphite",
    "string_tension":"19-27磅","head_size_cm2":68,"length_mm":675,
    "description":"Yonex 速度系列旗舰，头轻设计大幅提升挥拍速度，特制框角处理减少空气阻力，专为追求网前快攻和控制的选手打造。",
    "highlights":["头轻设计极速挥拍","特制减阻框角","网前控制利器"],
    "tags":["速度","网前","控制"],
    "suitable_height_min":155,"suitable_height_max":200,
    "suitable_weight_min":45,"suitable_weight_max":90,
    "suitable_age_min":14,"suitable_age_max":50,
  },
  {
    "sport":"badminton","brand":"Yonex","model":"Arcsaber 11 Pro",
    "image":"https://www.yonex.com/media/catalog/product/a/r/arc11p_grp_main_1.jpg",
    "price":1480,"weight_g":83,"balance":"even","flex":"medium",
    "skill_level":"advanced","gender":"unisex",
    "shaft_material":"HM Graphite + Nanometric","frame_material":"HM Graphite",
    "string_tension":"20-28磅","head_size_cm2":68,"length_mm":675,
    "description":"均衡型全能控制拍，拍线床弹性卓越，击球手感清晰，适合技术全面、追求精准落点的选手，兼顾攻防。",
    "highlights":["均衡全能控制型","拍线弹性优异","攻防兼备"],
    "tags":["控制","均衡","全能"],
    "suitable_height_min":155,"suitable_height_max":205,
    "suitable_weight_min":50,"suitable_weight_max":95,
    "suitable_age_min":14,"suitable_age_max":55,
  },
  {
    "sport":"badminton","brand":"Yonex","model":"Astrox 22",
    "image":"https://www.yonex.com/media/catalog/product/a/x/ax22_main_1.jpg",
    "price":480,"weight_g":77,"balance":"head_heavy","flex":"flexible",
    "skill_level":"beginner","gender":"unisex",
    "shaft_material":"Graphite","frame_material":"Graphite",
    "string_tension":"16-24磅","head_size_cm2":68,"length_mm":675,
    "description":"Yonex 入门级攻击型球拍，轻量化设计易于上手，适合初学者和休闲球友，性价比极高，是踏入羽毛球的理想首选。",
    "highlights":["77g超轻易上手","入门级性价比首选","Yonex品质保证"],
    "tags":["入门","轻量","性价比"],
    "suitable_height_min":140,"suitable_height_max":220,
    "suitable_weight_min":35,"suitable_weight_max":120,
    "suitable_age_min":8,"suitable_age_max":70,
  },
  {
    "sport":"badminton","brand":"Victor","model":"Thruster K 9900",
    "image":"https://www.victor.com.tw/Upload/ProductBase/Large/TK9900_main.jpg",
    "price":1980,"weight_g":83,"balance":"head_heavy","flex":"stiff",
    "skill_level":"advanced","gender":"male",
    "shaft_material":"High Carbon + PYROFIL","frame_material":"High Carbon",
    "string_tension":"22-30磅","head_size_cm2":68,"length_mm":675,
    "description":"Victor 顶级攻击拍，搭载三菱化学 PYROFIL 碳纤维，拍杆刚性极高，能量传导效率超强，是强力扣杀选手的不二之选。",
    "highlights":["PYROFIL三菱碳纤维","极高刚性超强扣杀","职业选手首选"],
    "tags":["进攻","扣杀","职业"],
    "suitable_height_min":168,"suitable_height_max":210,
    "suitable_weight_min":65,"suitable_weight_max":105,
    "suitable_age_min":16,"suitable_age_max":40,
  },
  {
    "sport":"badminton","brand":"Victor","model":"Auraspeed 90S",
    "image":"https://www.victor.com.tw/Upload/ProductBase/Large/ARS90S_main.jpg",
    "price":1280,"weight_g":82,"balance":"head_light","flex":"stiff",
    "skill_level":"advanced","gender":"unisex",
    "shaft_material":"High Carbon + PYROFIL","frame_material":"High Carbon",
    "string_tension":"20-28磅","head_size_cm2":68,"length_mm":675,
    "description":"Victor 顶级速度型球拍，超轻拍头配合高刚性拍杆，实现极速挥拍，专为追求速度和网前控制的单打选手设计。",
    "highlights":["82g超轻速度型","高刚性快速回位","单打速度首选"],
    "tags":["速度","单打","网前"],
    "suitable_height_min":155,"suitable_height_max":200,
    "suitable_weight_min":45,"suitable_weight_max":85,
    "suitable_age_min":14,"suitable_age_max":50,
  },
  {
    "sport":"badminton","brand":"Victor","model":"DriveX 10 Meta",
    "image":"https://www.victor.com.tw/Upload/ProductBase/Large/DX10META_main.jpg",
    "price":980,"weight_g":83,"balance":"even","flex":"medium",
    "skill_level":"intermediate","gender":"unisex",
    "shaft_material":"High Carbon","frame_material":"High Carbon",
    "string_tension":"20-27磅","head_size_cm2":68,"length_mm":675,
    "description":"Victor 进阶全能型球拍，均衡的重心设计让攻守转换更流畅，中等硬度拍杆适合技术成长中的中级选手。",
    "highlights":["均衡全能进阶首选","攻守转换流畅","性价比突出"],
    "tags":["均衡","进阶","全能"],
    "suitable_height_min":155,"suitable_height_max":205,
    "suitable_weight_min":50,"suitable_weight_max":95,
    "suitable_age_min":14,"suitable_age_max":55,
  },
  {
    "sport":"badminton","brand":"Li-Ning","model":"Axforce 100",
    "image":"https://img13.360buyimg.com/n1/jfs/t1/200038/35/36234/89432/65a1b2f3F1234/axforce100.jpg",
    "price":1580,"weight_g":86,"balance":"head_heavy","flex":"stiff",
    "skill_level":"advanced","gender":"male",
    "shaft_material":"T1100G Carbon Fiber","frame_material":"T1100G Carbon Fiber",
    "string_tension":"22-30磅","head_size_cm2":68,"length_mm":675,
    "description":"李宁旗舰攻击型球拍，采用航天级 T1100G 碳纤维，极致刚性提供无与伦比的扣杀力量，是李宁旗下最强攻击型号。",
    "highlights":["T1100G航天级碳纤维","极致刚性超强扣杀","国际顶级赛事用拍"],
    "tags":["进攻","专业","高端"],
    "suitable_height_min":168,"suitable_height_max":210,
    "suitable_weight_min":65,"suitable_weight_max":105,
    "suitable_age_min":18,"suitable_age_max":40,
  },
  {
    "sport":"badminton","brand":"Li-Ning","model":"Windstorm 78S",
    "image":"https://img13.360buyimg.com/n1/jfs/t1/windstorm78s.jpg",
    "price":680,"weight_g":78,"balance":"head_light","flex":"flexible",
    "skill_level":"beginner","gender":"female",
    "shaft_material":"Carbon Fiber","frame_material":"Carbon Fiber",
    "string_tension":"16-24磅","head_size_cm2":68,"length_mm":675,
    "description":"专为女性和青少年设计的轻量速度型球拍，超轻 78g 机身大幅降低击球负担，柔性拍杆容错率高，非常适合女性入门和提升。",
    "highlights":["78g超轻女性专属","柔性拍杆容错高","入门女性首选"],
    "tags":["轻量","女性","入门"],
    "suitable_height_min":145,"suitable_height_max":175,
    "suitable_weight_min":40,"suitable_weight_max":70,
    "suitable_age_min":10,"suitable_age_max":60,
  },
  {
    "sport":"badminton","brand":"Kawasaki","model":"Storm X6",
    "image":"https://img13.360buyimg.com/n1/jfs/kawasaki_x6.jpg",
    "price":280,"weight_g":80,"balance":"even","flex":"medium",
    "skill_level":"beginner","gender":"unisex",
    "shaft_material":"Aluminum + Carbon","frame_material":"Aluminum",
    "string_tension":"16-22磅","head_size_cm2":68,"length_mm":675,
    "description":"川崎入门实惠款，铝合金框架耐用易维护，均衡重心适合各种打法，是学生党和预算有限球友的高性价比选择。",
    "highlights":["280元亲民价格","铝碳混合耐用","均衡重心易操控"],
    "tags":["性价比","入门","耐用"],
    "suitable_height_min":140,"suitable_height_max":220,
    "suitable_weight_min":35,"suitable_weight_max":120,
    "suitable_age_min":8,"suitable_age_max":70,
  },

  # ───────────────── 网球拍 ─────────────────
  {
    "sport":"tennis","brand":"Wilson","model":"Pro Staff RF97 v14",
    "image":"https://www.wilson.com/en-us/media/catalog/product/W/R/WR125911_1.jpg",
    "price":2200,"weight_g":340,"balance":"head_light","flex":"stiff",
    "skill_level":"advanced","gender":"male",
    "shaft_material":"Braided Graphite","frame_material":"Braided Graphite",
    "string_tension":"50-60磅","head_size_cm2":613,"length_mm":685,
    "description":"费德勒签名款专业拍，340g 重量提供极致手感和控制力，小拍面 97in² 精准落点，传奇球员同款，专业选手的终极控制武器。",
    "highlights":["费德勒同款签名拍","340g极致手感控制","97in²精准小拍面"],
    "tags":["控制","专业","费德勒"],
    "suitable_height_min":175,"suitable_height_max":210,
    "suitable_weight_min":70,"suitable_weight_max":110,
    "suitable_age_min":18,"suitable_age_max":45,
  },
  {
    "sport":"tennis","brand":"Babolat","model":"Pure Aero 2023",
    "image":"https://www.babolat.com/media/catalog/product/1/0/101496_main.jpg",
    "price":1680,"weight_g":300,"balance":"head_heavy","flex":"medium",
    "skill_level":"intermediate","gender":"unisex",
    "shaft_material":"Graphite + FSI SPIN","frame_material":"Graphite",
    "string_tension":"50-59磅","head_size_cm2":645,"length_mm":685,
    "description":"纳达尔御用系列，FSI SPIN 专利弦孔技术提升上旋转速达 30%，中等硬度容错率佳，是追求大旋转球员的最爱。",
    "highlights":["纳达尔御用旋转神器","FSI SPIN提升30%上旋","均衡重量易于操控"],
    "tags":["旋转","纳达尔","进阶"],
    "suitable_height_min":160,"suitable_height_max":205,
    "suitable_weight_min":55,"suitable_weight_max":100,
    "suitable_age_min":14,"suitable_age_max":55,
  },
  {
    "sport":"tennis","brand":"Head","model":"Speed Pro 2024",
    "image":"https://www.head.com/media/catalog/product/2/3/235604_main.jpg",
    "price":1880,"weight_g":310,"balance":"head_light","flex":"medium",
    "skill_level":"advanced","gender":"unisex",
    "shaft_material":"Graphene 360+","frame_material":"Graphene 360+",
    "string_tension":"52-62磅","head_size_cm2":625,"length_mm":685,
    "description":"德约科维奇用拍，Graphene 360+ 技术实现全拍能量传导，攻守兼备的均衡型设计，适合技术全面追求速度与控制的进阶球员。",
    "highlights":["德约科维奇同款","Graphene360+全能传导","攻守兼备全能型"],
    "tags":["全能","德约","进阶"],
    "suitable_height_min":165,"suitable_height_max":208,
    "suitable_weight_min":60,"suitable_weight_max":100,
    "suitable_age_min":16,"suitable_age_max":50,
  },
  {
    "sport":"tennis","brand":"Wilson","model":"Blade 98 v9",
    "image":"https://www.wilson.com/en-us/media/catalog/product/W/R/WR079711_1.jpg",
    "price":1480,"weight_g":304,"balance":"head_light","flex":"medium",
    "skill_level":"intermediate","gender":"unisex",
    "shaft_material":"Graphite + Basalt","frame_material":"Graphite",
    "string_tension":"50-60磅","head_size_cm2":632,"length_mm":685,
    "description":"经典控制拍，玄武岩纤维提升手感，Parallel Drilling 弦孔设计增大击球甜区，灵活的头轻平衡让移动击球更顺畅。",
    "highlights":["玄武岩纤维手感出色","击球甜区增大15%","灵活控制易上手"],
    "tags":["控制","手感","均衡"],
    "suitable_height_min":158,"suitable_height_max":200,
    "suitable_weight_min":50,"suitable_weight_max":95,
    "suitable_age_min":14,"suitable_age_max":60,
  },
  {
    "sport":"tennis","brand":"Babolat","model":"Pure Drive 2021",
    "image":"https://www.babolat.com/media/catalog/product/1/0/101444_main.jpg",
    "price":1380,"weight_g":300,"balance":"head_heavy","flex":"stiff",
    "skill_level":"intermediate","gender":"unisex",
    "shaft_material":"Graphite + Cortex","frame_material":"Graphite",
    "string_tension":"50-59磅","head_size_cm2":645,"length_mm":685,
    "description":"全球最畅销网球拍之一，Cortex 纯净震动过滤技术减少肘部冲击，拍头较重提供良好威力，是初中级球员的销量王者。",
    "highlights":["全球销量第一网球拍","Cortex减振护手肘","威力与手感完美平衡"],
    "tags":["力量","热销","入门"],
    "suitable_height_min":155,"suitable_height_max":205,
    "suitable_weight_min":50,"suitable_weight_max":100,
    "suitable_age_min":12,"suitable_age_max":65,
  },
  {
    "sport":"tennis","brand":"Yonex","model":"VCORE 98 2023",
    "image":"https://www.yonex.com/media/catalog/product/v/c/vc98_flg_main_1.jpg",
    "price":1580,"weight_g":305,"balance":"head_light","flex":"medium",
    "skill_level":"intermediate","gender":"unisex",
    "shaft_material":"HM Graphite + Namd","frame_material":"HM Graphite",
    "string_tension":"45-60磅","head_size_cm2":632,"length_mm":685,
    "description":"Yonex 旗舰网球拍，Namd 纳米技术提升旋转力，均衡性能覆盖各种打法，造型独特、科技感强，是技术型球员的热门之选。",
    "highlights":["Namd纳米技术提升旋转","均衡性能覆盖各打法","Yonex顶级科技"],
    "tags":["旋转","均衡","科技"],
    "suitable_height_min":158,"suitable_height_max":205,
    "suitable_weight_min":52,"suitable_weight_max":98,
    "suitable_age_min":14,"suitable_age_max":58,
  },
  {
    "sport":"tennis","brand":"Wilson","model":"Clash 100 v2",
    "image":"https://www.wilson.com/en-us/media/catalog/product/W/R/WR074811_1.jpg",
    "price":1580,"weight_g":295,"balance":"even","flex":"flexible",
    "skill_level":"beginner","gender":"unisex",
    "shaft_material":"Carbon Mapping + FreeFlex","frame_material":"Graphite",
    "string_tension":"45-55磅","head_size_cm2":645,"length_mm":685,
    "description":"革命性柔性网球拍，FreeFlex 技术让拍框顺应击球弯曲后回弹，大幅降低手肘和手腕冲击，是初学者和中老年球友的护关节首选。",
    "highlights":["FreeFlex护腕护肘","超大甜区容错率高","初学者最友好网球拍"],
    "tags":["容错","护关节","入门"],
    "suitable_height_min":150,"suitable_height_max":200,
    "suitable_weight_min":45,"suitable_weight_max":95,
    "suitable_age_min":12,"suitable_age_max":75,
  },
  {
    "sport":"tennis","brand":"Head","model":"Boom Pro 2022",
    "image":"https://www.head.com/media/catalog/product/2/3/233522_main.jpg",
    "price":1280,"weight_g":298,"balance":"head_heavy","flex":"medium",
    "skill_level":"intermediate","gender":"unisex",
    "shaft_material":"Graphene 360+","frame_material":"Graphene 360+",
    "string_tension":"48-58磅","head_size_cm2":632,"length_mm":685,
    "description":"Head 旋转利器，特殊椭圆弦孔设计大幅增加旋转，轻盈重量搭配适中硬度，适合追求大旋转底线打法的进阶球员。",
    "highlights":["椭圆弦孔增强旋转","298g轻盈易操控","底线旋转球员专属"],
    "tags":["旋转","底线","进阶"],
    "suitable_height_min":158,"suitable_height_max":202,
    "suitable_weight_min":50,"suitable_weight_max":95,
    "suitable_age_min":14,"suitable_age_max":58,
  },
]
