# Generated by Django 6.0.2 on 2026-03-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Racket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('badminton', '羽毛球'), ('tennis', '网球')], max_length=20)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('price', models.IntegerField(help_text='人民币建议零售价')),
                ('weight_g', models.IntegerField(help_text='克')),
                ('balance', models.CharField(choices=[('head_heavy', '攻击型（头重）'), ('even', '均衡型'), ('head_light', '速度型（头轻）')], max_length=20)),
                ('flex', models.CharField(choices=[('flexible', '柔性'), ('medium', '中等'), ('stiff', '硬性')], max_length=20)),
                ('skill_level', models.CharField(choices=[('beginner', '入门'), ('intermediate', '进阶'), ('advanced', '专业')], max_length=20)),
                ('gender', models.CharField(choices=[('male', '男性'), ('female', '女性'), ('unisex', '通用')], default='unisex', max_length=10)),
                ('shaft_material', models.CharField(blank=True, max_length=100)),
                ('frame_material', models.CharField(blank=True, max_length=100)),
                ('string_tension', models.CharField(blank=True, help_text='如 20-28磅', max_length=50)),
                ('head_size_cm2', models.IntegerField(blank=True, help_text='拍框面积 cm²', null=True)),
                ('length_mm', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('highlights', models.JSONField(default=list, help_text='卖点列表，最多3条')),
                ('tags', models.JSONField(default=list, help_text='标签如 [进攻,扣杀]')),
                ('suitable_height_min', models.IntegerField(default=140)),
                ('suitable_height_max', models.IntegerField(default=220)),
                ('suitable_weight_min', models.IntegerField(default=40)),
                ('suitable_weight_max', models.IntegerField(default=120)),
                ('suitable_age_min', models.IntegerField(default=10)),
                ('suitable_age_max', models.IntegerField(default=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['brand', 'price'],
            },
        ),
    ]
