# Generated by Django 6.0.2 on 2026-03-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sport', models.CharField(choices=[('badminton', '羽毛球'), ('tennis', '网球'), ('both', '综合')], max_length=20)),
                ('country', models.CharField(default='中国', max_length=30)),
                ('province', models.CharField(default='广东省', max_length=30)),
                ('city', models.CharField(default='深圳市', max_length=30)),
                ('district', models.CharField(blank=True, default='', max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('business_hours', models.CharField(blank=True, default='', max_length=100)),
                ('price_from', models.IntegerField(default=0, help_text='起步价(元/小时)')),
                ('court_count', models.IntegerField(default=1, help_text='场地数')),
                ('floor_type', models.CharField(choices=[('wood', '木地板'), ('plastic', '塑胶'), ('cement', '水泥'), ('clay', '红土'), ('grass', '草地'), ('other', '其他')], default='wood', max_length=20)),
                ('has_parking', models.BooleanField(default=False)),
                ('parking_sufficient', models.BooleanField(default=False)),
                ('has_shower', models.BooleanField(default=False)),
                ('has_locker', models.BooleanField(default=False)),
                ('has_ac', models.BooleanField(default=True)),
                ('is_indoor', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=4.5)),
                ('review_count', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '场馆',
                'verbose_name_plural': '场馆列表',
                'db_table': 'venues',
                'ordering': ['name'],
            },
        ),
    ]
