# Generated by Django 6.0.2 on 2026-03-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sport', models.CharField(choices=[('badminton', '羽毛球'), ('tennis', '网球'), ('both', '综合')], max_length=20)),
                ('category', models.CharField(choices=[('international', '国际赛事'), ('national', '国内赛事'), ('local', '当地赛事')], max_length=20)),
                ('city', models.CharField(blank=True, default='', help_text='当地赛事所属城市', max_length=30)),
                ('summary', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '资讯',
                'verbose_name_plural': '资讯列表',
                'db_table': 'news',
                'ordering': ['-published_at'],
            },
        ),
    ]
