# Generated by Django 6.0.2 on 2026-03-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sport_pref',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
