# Generated by Django 6.0.2 on 2026-03-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_sport_pref'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_sport',
            field=models.CharField(default='badminton', max_length=20),
        ),
    ]
